#DEVELOPER PROFILE
#This file should not be published on Github but for the purpose of the assignment it will for now.
MONGODB_URI_FULL: mongodb+srv://lab2webshop:fb93CDRsnWoOUani@webshop.nwh0g2v.mongodb.net/?retryWrites=true&w=majority
DATABASE_NAME: webshop