#DEVELOPER PROFILE
MONGODB_URI_FULL: mongodb+srv://webshopuser:XNsootYOgPdYb7QH@cluster0.s0pykox.mongodb.net/?retryWrites=true&w=majority
DATABASE_NAME: Webshop
GOOGLE_CLIENT_ID: 235868178025-9so58h3737l4jrksgnsk4677v06mhjg4.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 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