spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${MONGODB_URI_FULL}
      database: ${DATABASE_NAME}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth?prompt=consent

logging:
  level:
    org.springframework.security: DEBUG